import { BlogPostPreview } from "@/components/BlogPostPreview";
import { Button } from "@/components/Button";
import { Code } from "@/components/Code";
import { Container } from "@/components/Container";
import { PageSection } from "@/components/PageSection";
import { Spacer } from "@/components/Spacer";
import { Subtitle } from "@/components/Subtitle";
import { Title } from "@/components/Title";
import Head from "next/head";
import Image from "next/image";
import headshot from "../../public/assets/images/headshot.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Louis Young</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Spacer />
          <section className="grid max-w-xl grid-cols-1 gap-12 lg:max-w-none lg:grid-cols-5 lg:items-center">
            <article className="order-2 lg:order-1 lg:col-span-3">
              <Title>
                Developing solutions to problems with quality software
              </Title>

              <Spacer size="small" />

              <p className="pr-12">
                Software developer with a passion for React, TypeScript, testing
                and educating.
              </p>

              <Spacer />

              <div className="inline-flex flex-col gap-6 lg:flex-row lg:items-center">
                <Button>Read my blog</Button>
                <Button variant="secondary">Talk to me</Button>
              </div>
            </article>

            <figure className="order-1 lg:order-2 lg:col-span-2">
              <Image
                src={headshot}
                alt="Louis Young"
                style={{ borderRadius: "36% 64% 51% 49% / 36% 44% 56% 64% " }}
              />
            </figure>
          </section>

          <Spacer size="large" />
        </Container>

        <Container>
          <PageSection className="lg:text-center">
            <article>
              <Subtitle>
                Developing{" "}
                <span className="font-normal text-primary">
                  solutions to problems
                </span>
                <br />
                with quality software.
              </Subtitle>

              <Spacer size="small" />

              <p className="lg:mx-auto lg:max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
                fuga cumque soluta deleniti neque dolorum voluptatem culpa amet
                dignissimos.
              </p>
            </article>
          </PageSection>
        </Container>

        <Container size="small">
          <PageSection className="grid grid-cols-1 gap-16 md:items-center md:justify-center lg:grid-cols-2">
            <article>
              <Subtitle>Lorem ipsum dolor sit amet dolor sit.</Subtitle>

              <Spacer size="small" />

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
                fuga cumque soluta deleniti neque dolorum voluptatem culpa amet
                dignissimos accusantium?
              </p>

              <Spacer size="small" />

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
                fuga cumque soluta deleniti neque dolorum voluptatem culpa amet
                dignissimos accusantium?
              </p>

              <Spacer size="small" />

              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
                fuga cumque soluta deleniti neque dolorum voluptatem culpa amet
                dignissimos accusantium?
              </p>
            </article>

            <figure>
              <img
                src="https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg"
                alt="Louis Young"
                className="rounded-md"
              />
            </figure>
          </PageSection>
        </Container>

        <Container>
          <PageSection>
            <div className="flex items-center justify-between gap-6">
              <Subtitle>Latest blog posts</Subtitle>

              <Button variant="secondary">View all blog posts</Button>
            </div>

            <Spacer />

            <div className="grid grid-cols-3 gap-8">
              <BlogPostPreview
                link=""
                image="https://res.cloudinary.com/kentcdodds-com/image/upload/c_fill,w_560,ar_3:4,q_auto,f_auto,b_rgb:e6e9ee/unsplash/photo-1494500764479-0c8f2919a3d8"
                title="Implicit and explicit returns in JavaScript"
                date="January 1, 2022"
              />

              <BlogPostPreview
                link=""
                image="https://res.cloudinary.com/kentcdodds-com/image/upload/c_fill,w_560,ar_3:4,q_auto,f_auto,b_rgb:e6e9ee/unsplash/photo-1494500764479-0c8f2919a3d8"
                title="Why functional state updates are important in React"
                date="January 1, 2022"
              />

              <BlogPostPreview
                link=""
                image="https://res.cloudinary.com/kentcdodds-com/image/upload/c_fill,w_560,ar_3:4,q_auto,f_auto,b_rgb:e6e9ee/unsplash/photo-1494500764479-0c8f2919a3d8"
                title="Why React state updates aren't immediately reflected"
                date="January 1, 2022"
              />
            </div>
          </PageSection>
        </Container>

        {/* <Code
          code={`const foo = 6;`}
          language="javascript"
          metastring=""
        ></Code> */}
      </main>
    </>
  );
}
